### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by exot** [francesco-kriegel/conexp-fx#1]
conexp-fx does not seem to have a license, and there should be a LICENSE file to indicate which one is used.  Please add it.

**Comment by exot** [comment]
In https://github.com/francesco-kriegel/conexp-fx/blob/master/src/main/java/be/humphreys/simplevoronoi/Edge.java the Apache License is mentioned, so you may want to add the corresponding Apace LICENSE file to your project.  Also add headers too all your source files containing an appropriate copyright notice.

**Comment by francesco-kriegel** [comment]
conexp-fx is released under Apache License 2.0 as denoted in the pom.xml.
LICENSE file has been added.
Class headers have been updated.
