### ISSUE TITLE
Unable to edit object or attribute default names

### ISSUE THREAD

**Issue by colingoldberg** [francesco-kriegel/conexp-fx#4]
Hi,

I successfully installed version 5.5.0 on my macbook pro. In a first test I created a context with 3 objects and 2 attributes, which were given names "Object 0", "Object 1", etc. But it does not do anything if I double-click or click right on a name and select "Edit", except to gray out the name. It does, however, allow me to save the context.

macosx version: 10.13.6

$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Please help.

Thanks

**Comment by francesco-kriegel** [comment]
Hi,

thanks for mentioning.  The issue should be fixed in the latest commit.

Ciao,
Francesco
